# Site
name              : "Lanz blog"
title             : "Lanz blog"
description       : '"Esa es la ventaja cuando uno lee, que sí sabe cómo son las cosas..."'
logo              : 'assets/images/lnz.png'
favicon           : 'assets/images/lnz.png'

# URL
url               : "https://lanzt.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl           : # the subpath of your site, e.g. "/blog"
repository        : "lanzt/lanzt.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

include           : ["_pages"]
google_analytics  : 'UA-xxxxxxxx-1'
disqus            : 'demowebsite'
mailchimp-list    : 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
permalink         : /:categories/:title
email             : lanz@lanz.com

# Authors
authors:
  lanz:
    name          : Lanz
    display_name  : Lanz
    gravatar      : e56154546cf4be74e393c62d1ae9f9d4
    email         : lanz@lanz.com
    twitter       : https://twitter.com/lanz_qtE
    description   : 'Expone por acá algunos de sus relatos, sus canciones más escuchadas, sus poemas más dedicados. Todo llevado al mundo de la ciberseguridad, porque "hay que divertirse..."'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
